# Session 2 Codes

In [1]:
# dependencies
import cv2
import numpy as np

# reading image
image = cv2.imread("Lucy.jpg")
print(f"image array is: {image}")

# showing image
cv2.imshow("cat", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# saving image
cv2.imwrite("lucy_green.jpg", image)

# shape of the image
print(f"image shape is: {image.shape}")

# channels
green_channel = image[:, :, 1]

# slicing
image[10:500, 100:600, :] = 0

image array is: [[[217 218 216]
  [217 218 216]
  [217 218 216]
  ...
  [167 173 178]
  [166 172 177]
  [165 171 176]]

 [[217 218 216]
  [217 218 216]
  [217 218 216]
  ...
  [167 173 178]
  [166 172 177]
  [165 171 176]]

 [[216 217 215]
  [216 217 215]
  [216 217 215]
  ...
  [167 173 178]
  [166 172 177]
  [165 171 176]]

 ...

 [[206 210 211]
  [204 208 209]
  [200 204 205]
  ...
  [167 173 180]
  [167 173 180]
  [167 173 180]]

 [[203 207 208]
  [201 205 206]
  [198 202 203]
  ...
  [167 173 180]
  [167 173 180]
  [166 172 179]]

 [[202 206 207]
  [200 204 205]
  [196 200 201]
  ...
  [167 173 180]
  [167 173 180]
  [167 173 180]]]
image shape is: (598, 960, 3)
