# Session 2 Codes

In [1]:
import cv2
import numpy as np

In [2]:
# dependencies


# reading image
image = cv2.imread("komodo.jpg")
print(f"image array is: {image}")

# showing image
cv2.imshow("komodo", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# saving image
cv2.imwrite("komodo_green.jpg", image)

# shape of the image
print(f"image shape is: {image.shape}")

# channels
green_channel = image[:, :, 1]

# slicing
image[10:500, 100:600, :] = 0

image array is: [[[218 193 159]
  [218 193 159]
  [218 193 159]
  ...
  [207 182 142]
  [207 182 142]
  [208 183 143]]

 [[218 193 159]
  [218 193 159]
  [218 193 159]
  ...
  [207 182 142]
  [208 183 143]
  [208 183 143]]

 [[218 193 159]
  [218 193 159]
  [218 193 159]
  ...
  [207 182 142]
  [208 183 143]
  [209 184 144]]

 ...

 [[113 161 167]
  [139 184 188]
  [147 187 192]
  ...
  [ 44  99 106]
  [120 178 184]
  [104 162 168]]

 [[152 197 201]
  [160 203 206]
  [170 209 211]
  ...
  [ 78 133 140]
  [102 157 164]
  [ 83 138 145]]

 [[170 213 216]
  [179 220 223]
  [176 214 216]
  ...
  [ 85 140 147]
  [107 162 171]
  [119 172 182]]]
image shape is: (637, 979, 3)


In [3]:
import cv2

ModuleNotFoundError: No module named 'cv2'