In [1]:
import cv2
import numpy as np

img1 = cv2.imread('Dog and Cat.jpg', cv2.IMREAD_COLOR)
img2 = cv2.resize(img1, (500, 500))
cv2.imshow('image', img1)
cv2.imshow('image2', img2)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [51]:
cap= cv2.VideoCapture('./city.mp4')
ret, frame=cap.read()
while True:
  ret, frame=cap.read()
  if not ret:
    print("Can't receive frame (stream end?). Exiting ...")
    break
  else:
    frame.resize(480, 640)
    cv2.imshow('frame', frame)
    cv2.waitKey(0)
    cap.release()
    cv2.destroyAllWindows()


Can't receive frame (stream end?). Exiting ...


True


In [48]:
print(frame)

[[[ 2  0  0]
  [ 2  0  0]
  [ 2  0  0]
  ...
  [ 2  0  0]
  [ 2  0  0]
  [ 2  0  0]]

 [[ 2  0  0]
  [ 2  0  0]
  [ 2  0  0]
  ...
  [ 2  0  0]
  [ 2  0  0]
  [ 2  0  0]]

 [[ 2  0  0]
  [ 2  0  0]
  [ 2  0  0]
  ...
  [ 2  0  0]
  [ 2  0  0]
  [ 2  0  0]]

 ...

 [[ 0  0 14]
  [ 0  0 15]
  [ 0  0 15]
  ...
  [ 0  0 23]
  [ 0  0 23]
  [ 0  0 23]]

 [[ 0  0 15]
  [ 0  0 15]
  [ 0  0 15]
  ...
  [ 0  0 23]
  [ 0  0 23]
  [ 0  0 23]]

 [[ 0  0 15]
  [ 0  0 15]
  [ 0  0 15]
  ...
  [ 0  0 23]
  [ 0  0 23]
  [ 0  0 23]]]


Can't receive frame (stream end?). Exiting ...
